/*
* Generated file
*
* Generated from: yang module name: netconf-exercise-impl yang module local name: netconf-exercise-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat May 26 22:53:54 IST 2018
*
* Do not modify this file unless it is present under src/main directory
*/
package org.sdnhub.odl.tutorial.netconf.exercise.impl;
public interface TutorialNetconfExerciseModuleMXBean {
    public javax.management.ObjectName getBindingAwareBroker();

    public void setBindingAwareBroker(javax.management.ObjectName bindingAwareBroker);

    public javax.management.ObjectName getRpcRegistry();

    public void setRpcRegistry(javax.management.ObjectName rpcRegistry);

    public javax.management.ObjectName getDataBroker();

    public void setDataBroker(javax.management.ObjectName dataBroker);

    public javax.management.ObjectName getNotificationService();

    public void setNotificationService(javax.management.ObjectName notificationService);

}
